# Generated by Django 3.2.9 on 2022-01-17 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
        ('news', '0011_comment_is_moderated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='authors.author'),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
